# Generated by Django 4.2.11 on 2025-11-03 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_alter_weeklyplan_options_weeklyplan_deleted_at_and_more'),
        ('clientsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weekly_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='plans.weeklyplan'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted'], name='clientsapp__is_dele_cb628c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['week_number'], name='clientsapp__week_nu_e206b6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['rep'], name='clientsapp__rep_id_802e81_idx'),
        ),
    ]
