# Generated by Django 4.2.11 on 2025-11-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientsapp', '0002_alter_client_options_client_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='weekly_plan',
        ),
    ]
