# Generated by Django 4.2.11 on 2025-11-02 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('week_no', models.PositiveIntegerField(blank=True, null=True)),
                ('aa_plan', models.CharField(blank=True, max_length=200)),
                ('targeted_line', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(blank=True, max_length=120)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('visit_objective', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('account', models.CharField(blank=True, max_length=200)),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_weekly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-archived_at', '-id'],
            },
        ),
    ]
