# Generated by Django 4.2.11 on 2025-11-02 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveweekly',
            options={'ordering': ['-archived_at', '-planned_date', '-id']},
        ),
        migrations.RenameField(
            model_name='archiveweekly',
            old_name='address',
            new_name='entity_address',
        ),
        migrations.RemoveField(
            model_name='archiveweekly',
            name='account',
        ),
        migrations.RemoveField(
            model_name='archiveweekly',
            name='targeted_line',
        ),
        migrations.RemoveField(
            model_name='archiveweekly',
            name='week_no',
        ),
        migrations.AddField(
            model_name='archiveweekly',
            name='product_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiveweekly',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='aa_plan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='archived_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_weeklies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='visit_objective',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
