# Generated by Django 4.2.11 on 2025-11-02 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0002_alter_archiveweekly_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiveweekly',
            old_name='product_line',
            new_name='targeted_line',
        ),
        migrations.RenameField(
            model_name='archiveweekly',
            old_name='week_number',
            new_name='week_no',
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='aa_plan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_weekly_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='visit_objective',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
