# Generated by Django 4.2.11 on 2025-11-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_rename_product_line_archiveweekly_targeted_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveweekly',
            name='total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archiveweekly',
            name='unique_clients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archiveweekly',
            name='week_no',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='archiveweekly',
            index=models.Index(fields=['week_no'], name='archives_ar_week_no_065216_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveweekly',
            index=models.Index(fields=['planned_date'], name='archives_ar_planned_f0fc65_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveweekly',
            index=models.Index(fields=['rep'], name='archives_ar_rep_id_824e88_idx'),
        ),
    ]
