# Generated by Django 4.2.11 on 2025-11-02 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientsapp', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvisit',
            name='actual_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyvisits', to='clientsapp.client'),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['visit_date'], name='visits_dail_visit_d_67e9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['rep'], name='visits_dail_rep_id_e60990_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['client'], name='visits_dail_client__3bd9d7_idx'),
        ),
    ]
