# Generated by Django 4.2.11 on 2025-11-02 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('visits', '0002_dailyvisit_actual_datetime_dailyvisit_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvisit',
            name='client_doctor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='time_shift',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='visit_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='weekly_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_visits', to='plans.weeklyplan'),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['weekly_plan'], name='visits_dail_weekly__eb6108_idx'),
        ),
    ]
