# Generated by Django 4.2.11 on 2025-11-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0003_dailyvisit_client_doctor_dailyvisit_time_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvisit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_daily_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='last_change',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_daily_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['is_deleted'], name='visits_dail_is_dele_612cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['deleted_at'], name='visits_dail_deleted_e691d5_idx'),
        ),
    ]
