# Generated by Django 4.2.11 on 2025-11-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_dailyvisit_deleted_at_dailyvisit_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyvisit',
            name='visits_dail_deleted_e691d5_idx',
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
