# Generated by Django 4.2.11 on 2025-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_remove_dailyvisit_visits_dail_deleted_e691d5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvisit',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='dailyvisit',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='dailyvisit',
            name='last_modified_by',
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['week_number'], name='visits_dail_week_nu_bb394f_idx'),
        ),
    ]
