# Generated by Django 4.2.11 on 2025-11-01 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_plan', models.CharField(max_length=200)),
                ('planned_date', models.DateField()),
                ('product_line', models.CharField(max_length=50)),
                ('entity_address', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('visit_objective', models.CharField(max_length=100)),
                ('other_objective', models.CharField(blank=True, max_length=255)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
