# Generated by Django 4.2.11 on 2025-11-03 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['-planned_date', '-id']},
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_weekly_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['is_deleted'], name='plans_weekl_is_dele_526646_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['status'], name='plans_weekl_status_b88cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['week_number'], name='plans_weekl_week_nu_9ec28b_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['rep'], name='plans_weekl_rep_id_0cd378_idx'),
        ),
    ]
