# Generated by Django 4.2.11 on 2025-11-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_weeklyplan_options_weeklyplan_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='weeklyplan',
            name='plans_weekl_is_dele_526646_idx',
        ),
        migrations.RemoveIndex(
            model_name='weeklyplan',
            name='plans_weekl_status_b88cf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='weeklyplan',
            name='plans_weekl_week_nu_9ec28b_idx',
        ),
        migrations.RemoveIndex(
            model_name='weeklyplan',
            name='plans_weekl_rep_id_0cd378_idx',
        ),
    ]
