# Generated by Django 4.2.11 on 2025-11-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_weeklyplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['-planned_date', '-id']},
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['planned_date'], name='plans_weekl_planned_ee8dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['rep'], name='plans_weekl_rep_id_0cd378_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['week_number'], name='plans_weekl_week_nu_9ec28b_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['status'], name='plans_weekl_status_b88cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['is_deleted'], name='plans_weekl_is_dele_526646_idx'),
        ),
    ]
